### ISSUE TITLE
Missing volume link in zammad-railsserver

### ISSUE THREAD

**Issue by legoheld** [zammad/zammad-docker-compose#15]
### Infos:

* Docker version: 1.10.1
* Docker-compose version: Deployed by rancher
* Operating system (Docker host): Ubuntu 14

### Expected behavior:

* Uploaded of images for logo should be visible in login screen

### Actual behavior:

* There is a broken image link.

Reason is probably because the uploaded image is not stored into the shared *data-zammad* volume. The *zammad-railsserver* has no volume reference like:
```
zammad-railsserver:
    image: zammad/zammad-docker-compose:zammad-railsserver
    labels:
      io.rancher.container.pull_image: always
    links:
      - zammad-elasticsearch
      - zammad-postgresql
    depends_on:
      - zammad
    restart: always
    volumes:
      - data-zammad:/home/zammad
```
This uploads the image into the container but the *zammad-nginx* container is not able to access it.
