### ISSUE TITLE
zammad-docker-compose with traefik and every session comes from the Docker host IP

### ISSUE THREAD

**Issue by RedJohn14** [zammad/zammad-docker-compose#184]
**Infos:**

Docker-compose version: docker-compose version 1.27.4
Operating system (Docker host): Ubuntu 20.04

**Expected behavior:**

Sessions in System -> Sessions should show the correct IPs.

**Steps to reproduce the behavior:**

Run zammad-docker-compose
Set up a reverse proxy, I used traefik that sits between zammad-docker-compose and the clients
Login into the web interface, and open the Sessions list.

In my **docker-compose.override.yml** I have set this:

```
  zammad-nginx:
    networks:
      - internal
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.zammad.rule=Host(`support.opsg.de`)
      - traefik.http.routers.zammad.entrypoints=websecure
      - traefik.http.routers.zammad.tls=true
      - traefik.http.routers.zammad.service=zammad
      - traefik.http.routers.zammad.tls.certresolver=tlschallenge
      - traefik.http.routers.zammad.middlewares=redirect-to-https
      - traefik.http.services.zammad.loadbalancer.server.port=80
```

I can work with my zammad instances without problems, BUT every session comes from traefik IP. If I used a new client and get E-Mail about this, the IP is like this:

```
Your Device: Mac, Chrome
Location (relativ): unknown
Your IP: 172.22.0.2
```

Any idea how can I fix this "error"?

Regards!
