### ISSUE TITLE
Help with simplifying docker-compose.yml

### ISSUE THREAD

**Issue by Azertooth** [zammad/zammad-docker-compose#202]
I'm trying to customize the compose file to follow a simplified, updated (from compose 2 to 3.8) and more readable structure. This is was i got until now but it currently doesn't work and i supposed there's something wrong related to variables and how containers communicates or to multiple commands of the zammad container:

```
version: '3.8'

services:

  zammad:
    depends_on:
      - zammad_es
      - zammad_mc
      - zammad_db
    container_name: zammad
    hostname: zammad
    image: zammad/zammad-docker-compose:zammad-4.0.0-20
    command: >
        ["zammad-init"]
        ["zammad-nginx"]
        ["zammad-railsserver"]
        ["zammad-scheduler"]
        ["zammad-websocket"]
    env_file:
      - ./envs/zammad.env
    volumes:
      - ./containers/zammad_stack/zammad:/opt/zammad
    restart: unless-stopped

  zammad_es:
    container_name: zammad_es
    hostname: zammad_es
    image: zammad/zammad-docker-compose:zammad-elasticsearch-4.0.0-20
    environment:
      - discovery.type=single-node
    volumes:
      - ./containers/zammad_stack/elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped

  zammad_mc:
    container_name: zammad_mc
    hostname: zammad_mc
    image: memcached:1.6.9-alpine
    command: memcached -m 256M
    restart: unless-stopped

  zammad_db:
    container_name: zammad_db
    hostname: zammad_db
    image: zammad/zammad-docker-compose:zammad-postgresql-4.0.0-20
    env_file:
      - ./envs/zammad.env
    volumes:
      - ./containers/zammad_stack/postgresql:/var/lib/postgresql/data
    restart: unless-stopped
```

```
# ./envs/zammad.env

ELASTICSEARCH_HOST=zammad_es
MEMCACHED_HOST=zammad_mc
ZAMMAD_RAILSSERVER_HOST=zammad_rs
ZAMMAD_WEBSOCKET_HOST=zammad_ws
POSTGRESQL_HOST=zammad_db
POSTGRESQL_USER=zammad
POSTGRESQL_PASS=zammad
POSTGRESQL_DB=zammad
```

please consider that:
- I do not use the backup container, i do that on my own
- I omitted port and network part, that's customized, it functions and it's not inherent to the problem
