### ISSUE TITLE
Elasticsearch is consuming insane amounts of RAM

### ISSUE THREAD

**Issue by jan-thoma** [zammad/zammad-docker-compose#256]
# Infos

* Docker version:
* Docker-compose version:
* Operating system (Docker host): Ubuntu 20.04

# Expected behavior

*Elasticsearch should consume reasonable amounts of RAM

# Actual behavior

*Elasticsearch consumes over 40GB of RAM

# Steps to reproduce the behavior

*Update Zammad from 4.x to 5.x the RAM usage skyrocketed.

**Comment by strickes** [comment]
I can confirm this. My installation is also swapping without need. Can we somehow limit the usage on elasticsearch?

**Comment by jan-thoma** [comment]
```
    zammad-elasticsearch:
        networks:
            - internal
        environment:
            - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
```

in docker-compose-overrride.yml solves the problem
