### ISSUE TITLE
Dedicated volume/mount for filesystem attachment storage break startup

### ISSUE THREAD

**Issue by lasat** [zammad/zammad-docker-compose#278]
# Infos

* Docker version: 20.10.14
* Docker-compose version: 1.29.2
* Operating system (Docker host): Debian 11

# Expected behavior

I tried to add a new volume to /opt/zammad/storage/fs to save attachments on external volume and expect that this location is protected from being overwritten and zammad-init container is able to handle it .

# Actual behavior

zammad-init container failed during rsync zammad files from tmp into /opt/zammad. '/storage/fs' is excluded from sync ([containers/zammad/docker-entrypoint.sh line 43](https://github.com/zammad/zammad-docker-compose/blob/defd3fbdcf0fbb52af541fd1d6f3285f6501aece/containers/zammad/docker-entrypoint.sh#L43)) but the --delete option of rsync tries to cleanup the destination and fail.

# Steps to reproduce the behavior

Add a volume to zammad-init container.

```
  zammad-init:
    command: ["zammad-init"]
    ...
    volumes:
      - zammad-data:/opt/zammad
      - ./storage:/opt/zammad/storage/fs
```
