### ISSUE TITLE
Nginx gets stucked: "Starting Nginx"

### ISSUE THREAD

**Issue by 1Shiroyuuki1** [zammad/zammad-docker-compose#330]
* Docker version: 23.0.1
* Docker-compose version: zammad/zammad-docker-compose:5.4.0
* Operating system (Docker host): Ubuntu 20.04

# Expected behavior

* Any kind of log to identifiy problems or in the best case a running Nginx

# Actual behavior

* `waiting for init container to finish install or update...
starting nginx...`

# Steps to reproduce the behavior

- git clone [GitHub - zammad/zammad-docker-compose: Zammad Docker images for docker-compose](https://github.com/zammad/zammad-docker-compose)
- Adjusted the docker-compose.yml by adding additional envs (Traefik as Reverse Proxy) and proper network
- docker-compose up -d
- All services came up without any error but nginx seems to be stucked

```
 version: '3'
  networks:
    traefik:
      external:
        name: traefik
    zammad:
      name: zammad
  services:
  #------------------------------------------------------------Zammad Elasticsearch-------------------------------#
    zammad-elasticsearch:
      image: bitnami/elasticsearch:8.5.1
      restart: ${RESTART}
      volumes:
        - ./elasticsearch-data:/usr/share/elasticsearch/data
      environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - ingest.geoip.enabled=false
      networks:
      - zammad
  #------------------------------------------------------------Zammad Init ---------------------------------------#
    zammad-init:
      command: ["zammad-init"]
      depends_on:
        - zammad-postgresql
      environment:
        - MEMCACHE_SERVERS=${MEMCACHE_SERVERS}
        - POSTGRESQL_USER=${POSTGRES_USER}
        - POSTGRESQL_PASS=${POSTGRES_PASS}
        - REDIS_URL=${REDIS_URL}
      image: ${IMAGE_REPO}:${VERSION}
      restart: on-failure
      volumes:
        - ./zammad-data:/opt/zammad
      networks:
      - zammad
  #------------------------------------------------------------Zammad Memory Caching-------------------------------#
    zammad-memcached:
      command: memcached -m 256M
      image: memcached:1.6.17-alpine
      restart: ${RESTART}
      networks:
      - zammad
  #------------------------------------------------------------Zammad Nginx ---------------------------------------#
    zammad-nginx:
      command: ["zammad-nginx"]
      depends_on:
        - zammad-railsserver
      image: ${IMAGE_REPO}:${VERSION}
      restart: ${RESTART}
      volumes:
        - ./zammad-data:/opt/zammad
        - ./default:/data/zammad
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.zammad.rule=Host(`xxx`)"
        - "traefik.http.routers.zammad.tls.certresolver=letsencrypt"
        - "traefik.http.routers.zammad.entrypoints=websecure"
        - "traefik.http.routers.zammad.service=zammad"
        - "traefik.http.services.zammad.loadbalancer.server.port=8080"
      expose:
        - "8080"
      environment:
       - RAILS_TRUSTED_PROXIES=['127.0.0.1', '::1', 'traefik']
       - NGINX_SERVER_SCHEME=https
      networks:
        - zammad
        - traefik
  #------------------------------------------------------------Zammad Postgres --------------------------------------#
    zammad-postgresql:
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASS}
      image: postgres:${POSTGRES_VERSION}
      restart: ${RESTART}
      volumes:
        - ./postgresql-data:/var/lib/postgresql/data
      networks:
      - zammad
  #------------------------------------------------------------Zammad Railserver ------------------------------------#
    zammad-railsserver:
      command: ["zammad-railsserver"]
      depends_on:
        - zammad-memcached
        - zammad-postgresql
        - zammad-redis
      environment:
        - MEMCACHE_SERVERS=${MEMCACHE_SERVERS}
        - REDIS_URL=${REDIS_URL}
      image: ${IMAGE_REPO}:${VERSION}
      restart: ${RESTART}
      volumes:
        - ./zammad-data:/opt/zammad
      networks:
      - zammad
  #------------------------------------------------------------Zammad Redis -----------------------------------------#
    zammad-redis:
      image: redis:7.0.5-alpine
      restart: ${RESTART}
      networks:
        - zammad
  #------------------------------------------------------------Zammad Scheduler -------------------------------------#
    zammad-scheduler:
      command: ["zammad-scheduler"]
      depends_on:
        - zammad-memcached
        - zammad-railsserver
        - zammad-redis
      environment:
        - MEMCACHE_SERVERS=${MEMCACHE_SERVERS}
        - REDIS_URL=${REDIS_URL}
      image: ${IMAGE_REPO}:${VERSION}
      restart: ${RESTART}
      volumes:
        - ./zammad-data:/opt/zammad
      networks:
        - zammad
  #------------------------------------------------------------Zammad Websocket -------------------------------------#
    zammad-websocket:
      command: ["zammad-websocket"]
      depends_on:
        - zammad-memcached
        - zammad-railsserver
        - zammad-redis
      environment:
        - MEMCACHE_SERVERS=${MEMCACHE_SERVERS}
        - REDIS_URL=${REDIS_URL}
      image: ${IMAGE_REPO}:${VERSION}
      restart: ${RESTART}
      volumes:
        - ./zammad-data:/opt/zammad
      networks:
        - zammad

  volumes:
    elasticsearch-data:
      driver: local
    postgresql-data:
      driver: local
    zammad-data:
      driver: local
```

**Traefik Dashboard shows me that, the route is created and reachable:**
![image](https://user-images.githubusercontent.com/72495090/229501600-072ad342-0e84-4d93-92dc-47c407d3e01a.png)

Other Applications which are also using Nginx are reachable so i guess this might be a bug in the current zammad-docker-compose stack.
