### ISSUE TITLE
Running on Localhost:8081 not work (Podman)

### ISSUE THREAD

**Issue by Mannshoch** [zammad/zammad-docker-compose#394]
# Infos

* Docker version: `podman version 4.3.1`
* Docker-compose version: `podman-compose version 1.0.6`
* Operating system (Docker host): `Ubuntu 23.10`
* No domain or ssl certificate. Only use on localhost

# Expected behavior

* follow #209 allows me to run Zammad on a certain Port

# Actual behavior

* no access to zammad

# Steps to reproduce the behavior

* copy `docker-compose.yml`, `docker-compose.override-local.yml`, `docker-compose.override.yml` into a directory
* create `.env`
```
ELASTICSEARCH_VERSION=8.8.0
IMAGE_REPO=ghcr.io/zammad/zammad
MEMCACHE_SERVERS=zammad-memcached:11211
MEMCACHE_VERSION=1.6.20-alpine
POSTGRES_DB=zammad_production
POSTGRES_PASS=zammad
POSTGRES_USER=zammad
POSTGRES_HOST=zammad-postgresql
POSTGRES_PORT=5432
POSTGRES_VERSION=15.3-alpine
REDIS_URL=redis://zammad-redis:6379
REDIS_VERSION=7.0.5-alpine
RESTART=always
VERSION=latest
```
* Modify `docker-compose.yml` (according to #209) and replaced Port to expose.
```
  zammad-nginx:
    <<: *zammad-service
    command: ["zammad-nginx"]
    expose:
      - "8081"
```
* Modify `docker-compose.overrride.yml` 
```
---
version: '2'

services:

  zammad-nginx:
    ports:
      - 8081:8081
      
  zammad-service:
    environment:
      NGINX_PORT: 8081
```
* Run `podman-compose up -d --build`
* everything starts but  `zammad_zammad-init_1` stop after a while.
* `zammad_zammad-nginx_1` - 0.0.0.0:8081 → 8081/tcp (cockpit webconsole with podman plugin)
