### ISSUE TITLE
FIX: Elasticsearch out of memory after 24 hours.

### ISSUE THREAD

**Issue by chasgames** [zammad/zammad-docker-compose#42]
After 24 hours of install on a 2GB Ram machine, out of memory, changed all "restart:" to unless-stopped as couldn't even stop the thing!.

 
Add these environment options to docker-compose.yml
ES_HEAP_SIZE=200m and ES_JAVA_OPTS="-Xms200m -Xmx200m"

Worked for me, running smoothly now.

```
 zammad-elasticsearch:
    image: zammad/zammad-docker-compose:zammad-elasticsearch
    labels:
      io.rancher.container.pull_image: always
    restart: unless-stopped
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
    environment:
      - ES_HEAP_SIZE=200m
      - ES_JAVA_OPTS="-Xms200m -Xmx200m"
```
