### ISSUE TITLE
Update the proxy example to fit the current version of compose file

### ISSUE THREAD

**Issue by Jan-NiklasB** [zammad/zammad-docker-compose#430]
# Infos

* Docker version: 27.2.1
* Docker-compose version: 1.27.4
* Operating system (Docker host): Ubuntu 22.04 LTS

# Expected behavior

* Adding the "environment" section to the zammad-nginx section with the vars needed like "VIRTUAL_HOST: xyz.domain.tld" works out of the box

# Actual behavior

* I needed to try around for some hours, since adding the environment-section to the zammad-nginx section in the current docker-compose.yml resulted in the nginx getting stuck on waiting for the init container.

The final solution was to omit the environment section in the zammad-nginx section and instead add the vars to the x-shared -> environment-section

# Steps to reproduce the behavior

* Setup the current version and modify the the zammad-nginx section as follows:

```
zammad-nginx:
    environment:
      VIRTUAL_HOST: ${VHOST:-support.domain.tld}
      LETSENCRYPT_HOST: ${LE_HOST:-support.domain.tld}
    <<: *zammad-service
    command: ["zammad-nginx"]
    expose:
      - "${NGINX_PORT:-8080}"
    ports:
      - "${NGINX_EXPOSE_PORT:-8080}:${NGINX_PORT:-8080}"
    depends_on:
      - zammad-railsserver
```
