### ISSUE TITLE
FYI: thanks to the introduction of virtual host variable in x-shared you broke our setup

### ISSUE THREAD

**Issue by oxidsimongassenschmidt** [zammad/zammad-docker-compose#471]
We use following NGINX Proxy:
https://hub.docker.com/r/jwilder/nginx-proxy

this proxy routes the traffic to:
"Provided your DNS is setup to forward foo.bar.com to the host running nginx-proxy, the request will be routed to a container with the VIRTUAL_HOST env var set."
According to docker compose config all hosts now have a VIRTUAL_HOST: null entry.
So we got a ssl handshake error. We could resolve the error with removing this entry in the docker-compose.yml. We have to remove this every update.

Please be in future more careful with introducing variables in x-shared. 
Also please remove this specific variable from the standard yml.

**Comment by MrGeneration** [comment]
You're running a non standard Zammad compose stack. You're supposed to check for breaking changes - especially on custom setups like yours.

**Comment by mdoerfel** [comment]
The recommended way of changing a (any) docker compose stack is a local file _docker-compose.override.yml_. It extends or replaces the definitions in the default docker-compose.yml.

We use nginx-proxy as well, and our docker-compose.override.yml looks like this:

```
services:
  zammad-nginx:
    networks:
      - default
      - extern
    environment:
      VIRTUAL_HOST: zammad.example.com
      VIRTUAL_PORT: 8080
      CERT_NAME: example.com
    ports: !reset []
      # Reset ports to avoid exposure of the service to the outside world.
      # This service should only be available via nginxproxy.

networks:
    default:
    extern:
        external: true
        name: extern
```

Note: This is for release v13.0.5, but in principle it can also be used to override VIRTUAL_HOST in v13.3.2.

As the official git repository does not contain a docker-compose.override.yml, there is no conflict with updates. Nonetheless, as @MrGeneration says, you're supposed to check for changes.
