### ISSUE TITLE
zammad-railsserver not detecting postgress

### ISSUE THREAD

**Issue by Starfox64** [zammad/zammad-docker-compose#48]
### Infos:

* Docker version: 17.06.1-ce
* Docker-compose version: Rancher 1.6.7
* Operating system (Docker host): Ubuntu 16.04

### Expected behavior:

zammad-railsserver detects postgress and starts.

### Actual behavior:

```
9/28/2017 11:08:03 AMzammad railsserver waiting for postgresql server to be ready...
9/28/2017 11:08:08 AMzammad railsserver waiting for postgresql server to be ready...
9/28/2017 11:08:13 AMzammad railsserver waiting for postgresql server to be ready...
9/28/2017 11:08:18 AMzammad railsserver waiting for postgresql server to be ready...
```

### Steps to reproduce the behavior:
Create a new stack with the following docker-compose.yml

```yml
version: '2'
volumes:
  data-zammad:
    driver: local
services:
  zammad-scheduler:
    image: zammad/zammad-docker-compose:zammad-scheduler
    links:
    - postgresql:postgresql
    - zammad:zammad
    - elasticsearch:elasticsearch
    labels:
      io.rancher.container.pull_image: always
  zammad:
    image: zammad/zammad-docker-compose:zammad
    volumes:
    - data-zammad:/home/zammad
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  elasticsearch:
    image: zammad/zammad-docker-compose:zammad-elasticsearch
    labels:
      io.rancher.container.pull_image: always
  postgresql:
    image: zammad/zammad-docker-compose:zammad-postgresql
    labels:
      io.rancher.container.pull_image: always
  nginx:
    image: zammad/zammad-docker-compose:zammad-nginx
    volumes:
    - data-zammad:/home/zammad
    links:
    - zammad-websocket:zammad-websocket
    - zammad-railsserver:zammad-railsserver
    ports:
    - 8080:80/tcp
    labels:
      io.rancher.container.pull_image: always
  zammad-railsserver:
    image: zammad/zammad-docker-compose:zammad-railsserver
    links:
    - postgresql:postgresql
    - zammad:zammad
    - elasticsearch:elasticsearch
    labels:
      io.rancher.container.pull_image: always
  zammad-websocket:
    image: zammad/zammad-docker-compose:zammad-websocket
    links:
    - postgresql:postgresql
    - zammad:zammad
    labels:
      io.rancher.container.pull_image: always
```
