### ISSUE TITLE
Add zammad-var again?

### ISSUE THREAD

**Issue by niondir** [zammad/zammad-docker-compose#487]
Hi,
after playing around a lot with the docker setup I found it quiet difficult to update from `v5.0.0-7` to `v6.0.0-131` to `v6.5.0-53`

To ease the update path it would help a lot to keep `zammad-var:/opt/zammad/var` in the docker-compose file.

Especially since there are many bugs fixed on the path to the latest docker-compose.yml version like the database host that was not taken from .env for some versions.

I will also check the update path starting from `4.0.0-13` but getting from there to `5.0.0-7` was no big issue.

**Comment by waja** [comment]
> To ease the update path it would help a lot to keep zammad-var:/opt/zammad/var in the docker-compose file.

You can keep the definition in a separate compose file and add it with `-f` when starting the stack while doing the migration for example.

**Comment by niondir** [comment]
That's basically what I did. I have quiet a stack of changes in my `docker-compose.override.yml`

- Using traefik
- Using external postgres
- adding the volume at /opt/zammad/var

In case someone interested. 

**docker-compose.override.yml**

```
---
networks:
  postgres:
    name: "postgres"
    external: true
  http:
    name: "traefik-public"
    external: true

x-shared:
  zammad-service: &zammad-service
    networks:
      - default
      - postgres
    volumes:
      - zammad-var:/opt/zammad/var

services:
  zammad-backup:
    <<: *zammad-service
    networks:
      - default
      - postgres
    # backups are not needed during migration
    # profiles:
    #   - do-not-start

  #  zammad-elasticsearch:
  # Disable Elasticsearch when provided externally
  #    # Also needs .env ELASTICSEARCH_ENABLED=false
  #    profiles:
  #      - do-not-start

  zammad-init:
    <<: *zammad-service
    networks:
      - default
      - postgres

  #  zammad-memcached:
  #    networks:
  #      - default

  zammad-nginx:
    <<: *zammad-service
    ports: !reset []
    networks:
      - default
      - postgres
      - http
    environment:
      # Needed to avoid CSRF issues on Login
      NGINX_SERVER_SCHEME: "https"
    labels:
      - traefik.enable=true
      - traefik.http.routers.zammad.rule=Host(`zammad.example.com`)
      - traefik.http.routers.zammad-secure.rule=Host(`zammad.example.com`)
      - traefik.http.routers.zammad.tls=true
      - traefik.http.routers.zammad.tls.certresolver=letsencrypt
      - traefik.http.services.zammad.loadbalancer.server.port=8080

  zammad-railsserver:
    <<: *zammad-service
    networks:
      - default
      - postgres

  zammad-postgresql:
    profiles:
      - do-not-start

  zammad-scheduler:
    <<: *zammad-service
    networks:
      - default
      - postgres

  zammad-websocket:
    <<: *zammad-service
    networks:
      - default
      - postgres

volumes:
  # Required for Zammad < v6.0.0
  zammad-var:
    driver: local
```
