### ISSUE TITLE
Scheduler not working

### ISSUE THREAD

**Issue by hhoechtl** [zammad/zammad-docker-compose#55]
### Infos:

* Docker version: 17.05.0-ce
* Docker-compose version: 1.9.0, build 2585387
* Operating system (Docker host): Ubuntu 16.04.3 LTS

### Expected behavior:

* Scheduler running and monitoring showing state run

### Actual behavior:

* Scheduler container is running and shows message `scheduler can access raillsserver now...`
* Railsserver is running but no mails are received
* Opening the Monitoring tab shows `scheduler not running`

### Steps to reproduce the behavior:

I just updated my old environment which was running Zammad 1.5.0 to 2.1.1 with my images built from this repository but tagged with 2.1.1 as there's currently no image with that version tag.

* Deploy current docker-compose version

The railsserver seems to be running as expected, the log doesn't show any useful hints:
```
14.10.2017 18:26:11drop indexes...
14.10.2017 18:26:11create indexes...
14.10.2017 18:26:11reload data...
14.10.2017 18:26:11 reload Organization
14.10.2017 18:26:11  - started at 2017-10-14 16:26:11 UTC
14.10.2017 18:26:12  - took 0 seconds
14.10.2017 18:26:12 reload User
14.10.2017 18:26:12  - started at 2017-10-14 16:26:12 UTC
14.10.2017 18:26:22  - took 10 seconds
14.10.2017 18:26:22 reload Ticket
14.10.2017 18:26:22  - started at 2017-10-14 16:26:22 UTC
14.10.2017 18:32:01  - took 338 seconds
14.10.2017 18:32:01starting zammad...
14.10.2017 18:32:01zammad will be accessable on http://localhost in some seconds
14.10.2017 18:32:01Puma starting in single mode...
14.10.2017 18:32:01* Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller
14.10.2017 18:32:01* Min threads: 5, max threads: 30
14.10.2017 18:32:01* Environment: production
14.10.2017 18:32:04* Listening on tcp://0.0.0.0:3000
14.10.2017 18:32:04Use Ctrl-C to stop
14.10.2017 18:32:102017-10-14T16:32:10Z:client(6981477649) request spool data > '2017-10-14T16:21:27Z'
14.10.2017 18:32:102017-10-14T16:32:10Z:client(6981477649) send spool:sent event
14.10.2017 18:32:112017-10-14T16:32:11Z:client(6981477649) do not send broadcast to it self
14.10.2017 18:32:262017-10-14 16:32:26 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
14.10.2017 18:32:26---
14.10.2017 18:32:302017-10-14 16:32:30 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
14.10.2017 18:32:30---
14.10.2017 18:32:342017-10-14 16:32:34 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
14.10.2017 18:32:34---
14.10.2017 18:32:382017-10-14 16:32:38 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
14.10.2017 18:32:38---
14.10.2017 18:32:422017-10-14 16:32:42 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
14.10.2017 18:32:42---
14.10.2017 18:32:472017-10-14 16:32:47 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
14.10.2017 18:32:47---
14.10.2017 18:32:512017-10-14 16:32:51 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
14.10.2017 18:32:51---
```

**Comment by monotek** [comment]
Maybe not the best idea as 2.1.1 is the unstable development branch.

Whats the output of:
* docker container ls

**Comment by hhoechtl** [comment]
2.1.1. is a version tag and is therefore supposed to be a stable release. If you need to tag a development state why so ever, you should use 2.1.1-dev to indicate an unstable testing version.

docker container ls
```
34bf149e1441        1drop/zammad:zammad-211               "/.r/r /docker-ent..."   14 hours ago        Up 14 hours                               r-Zammad-websocket-1-b71e6464
45c99ada2d72        1drop/zammad:zammad-211               "/.r/r /docker-ent..."   14 hours ago        Up 14 hours                               r-Zammad-scheduler-1-73c3b744
660484fe2348        1drop/zammad:nginx                    "/.r/r nginx -g 'd..."   14 hours ago        Up 14 hours                               r-Zammad-nginx-1-8f878791
d39c81d7bf09        1drop/zammad:zammad-211               "/.r/r /docker-ent..."   14 hours ago        Up 14 hours                               r-Zammad-zammad-1-d990d3cf
2bca183b7dba        1drop/zammad:elasticsearch            "/.r/r /bin/bash b..."   14 hours ago        Up 14 hours                               r-Zammad-elasticsearch-1-b98c0f21
6773b49450e2        postgres:9.6                          "/.r/r docker-entr..."   14 hours ago        Up 14 hours                               r-Zammad-postgresql-1-884eae15
```

**Comment by hhoechtl** [comment]
I now downgraded to the stable 2.0.0:
```yaml
version: '2'
volumes:
  data-zammad:
    driver: local
services:
  zammad-scheduler:
    image: zammad/zammad-docker-compose:zammad-2.0.0-36
    stdin_open: true
    volumes:
    - data-zammad:/home/zammad
    tty: true
    links:
    - postgresql:zammad-postgresql
    - elasticsearch:zammad-elasticsearch
    - zammad-railsserver:zammad-railsserver
    command:
    - zammad-scheduler
    labels:
      io.rancher.container.pull_image: always
  elasticsearch:
    image: zammad/zammad-docker-compose:zammad-elasticsearch-2.0.0-36
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  postgresql:
    image: postgres:9.6
    stdin_open: true
    volumes:
    - /opt/zammad/pgsql:/var/lib/postgresql/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
  zammad-nginx:
    image: zammad/zammad-docker-compose:zammad-nginx-2.0.0-36
    stdin_open: true
    volumes:
    - data-zammad:/home/zammad
    tty: true
    links:
    - zammad-railsserver:zammad-railsserver
    - zammad-websocket:zammad-websocket
    labels:
      io.rancher.container.pull_image: always
  zammad-railsserver:
    image: zammad/zammad-docker-compose:zammad-2.0.0-36
    environment:
      RAILS_SERVER: unicorn
    stdin_open: true
    volumes:
    - data-zammad:/home/zammad
    tty: true
    links:
    - postgresql:zammad-postgresql
    - elasticsearch:zammad-elasticsearch
    command:
    - zammad-railsserver
    labels:
      io.rancher.container.pull_image: always
  zammad-websocket:
    image: zammad/zammad-docker-compose:zammad-2.0.0-36
    stdin_open: true
    volumes:
    - data-zammad:/home/zammad
    tty: true
    links:
    - postgresql:zammad-postgresql
    - zammad-railsserver:zammad-railsserver
    command:
    - zammad-websocket
    labels:
      io.rancher.container.pull_image: always
```

After some restarts it now works as expected.
