### ISSUE TITLE
Rail server fails to start with docker compose

### ISSUE THREAD

**Issue by gerroon** [zammad/zammad-docker-compose#93]
Hi

I cant get docker-compose up runniong properly. It seems like the rail server fails to start. 

I was able to run simple docker container no problem.

The only thing I did was to change the override yml to

```
 version: '2'                                                                                                                                                                                
  services:                                                                                                                                                                                   
                                                                                                                                                                                              
    zammad-nginx:                                                                                                                                                                             
      ports:                                                                                                                                                                                  
        - "4080:80" 
```

I am using Debian Buster, 
```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:53 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

```
zammad-elasticsearch_1  | [2019-02-03T19:26:43,878][INFO ][o.e.c.m.MetaDataMappingService] [oFTVSF1] [zammad_production/zD9qO_hLQzm3oef9f8a50w] update_mapping [Ticket]                      
zammad-elasticsearch_1  | [2019-02-03T19:26:43,996][INFO ][o.e.c.m.MetaDataMappingService] [oFTVSF1] [zammad_production/zD9qO_hLQzm3oef9f8a50w] update_mapping [Organization]                
zammad_zammad-init_1 exited with code 0                                                                                                                                                      
zammad-railsserver_1    | starting railsserver...                                   
```

```
zammad-nginx_1          | starting nginx...                                                                                                                                          [16/5032]
zammad-railsserver_1    | => Booting Puma                                                                                                                                                    
zammad-railsserver_1    | => Rails 5.1.6.1 application starting in production                                                                                                                
zammad-railsserver_1    | => Run `rails server -h` for more startup options                                                                                                                  
zammad-railsserver_1    | Puma starting in single mode...                                                                                                                                    
zammad-railsserver_1    | * Version 3.11.0 (ruby 2.4.4-p296), codename: Love Song                                                                                                            
zammad-railsserver_1    | * Min threads: 5, max threads: 30
zammad-railsserver_1    | * Environment: production
zammad-railsserver_1    | * Listening on tcp://[::]:3000                                                                                                                                     
zammad-railsserver_1    | Exiting                                                                                                                                                            
zammad-railsserver_1    | /usr/local/bundle/gems/puma-3.11.0/lib/puma/binder.rb:270:in `initialize': Address family not supported by protocol - socket(2) for "::" port 3000 (Errno::EAFNOSUPP
ORT)                                                                                                                                                                                         
zammad-railsserver_1    |       from /usr/local/bundle/gems/puma-3.11.0/lib/puma/binder.rb:270:in `new'                                                                                      
zammad-railsserver_1    |       from /usr/local/bundle/gems/puma-3.11.0/lib/puma/binder.rb:270:in `add_tcp_listener'                                                                         
zammad-railsserver_1    |       from /usr/local/bundle/gems/puma-3.11.0/lib/puma/binder.rb:105:in `block in parse'                                                                           
zammad-railsserver_1    |       from /usr/local/bundle/gems/puma-3.11.0/lib/puma/binder.rb:88:in `each'                                                                                      
zammad-railsserver_1    |       from /usr/local/bundle/gems/puma-3.11.0/lib/puma/binder.rb:88:in `parse'                                                                                     
zammad-railsserver_1    |       from /usr/local/bundle/gems/puma-3.11.0/lib/puma/runner.rb:144:in `load_and_bind'                                                                            
zammad-railsserver_1    |       from /usr/local/bundle/gems/puma-3.11.0/lib/puma/single.rb:87:in `run'
zammad-railsserver_1    |       from /usr/local/bundle/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
zammad-railsserver_1    |       from /usr/local/bundle/gems/puma-3.11.0/lib/rack/handler/puma.rb:69:in `run'
zammad-railsserver_1    |       from /usr/local/bundle/gems/rack-2.0.6/lib/rack/server.rb:297:in `start'
zammad-railsserver_1    |       from /usr/local/bundle/gems/railties-5.1.6.1/lib/rails/commands/server/server_command.rb:44:in `start'
zammad-railsserver_1    |       from /usr/local/bundle/gems/railties-5.1.6.1/lib/rails/commands/server/server_command.rb:135:in `block in perform'
zammad-railsserver_1    |       from /usr/local/bundle/gems/railties-5.1.6.1/lib/rails/commands/server/server_command.rb:130:in `tap'
zammad-railsserver_1    |       from /usr/local/bundle/gems/railties-5.1.6.1/lib/rails/commands/server/server_command.rb:130:in `perform'
zammad-railsserver_1    |       from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
zammad-railsserver_1    |       from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
zammad-railsserver_1    |       from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
zammad-railsserver_1    |       from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch' 
zammad-railsserver_1    |       from /usr/local/bundle/gems/railties-5.1.6.1/lib/rails/command/base.rb:63:in `perform'
zammad-railsserver_1    |       from /usr/local/bundle/gems/railties-5.1.6.1/lib/rails/command.rb:44:in `invoke'
zammad-railsserver_1    |       from /usr/local/bundle/gems/railties-5.1.6.1/lib/rails/commands.rb:16:in `<top (required)>'
zammad-railsserver_1    |       from bin/rails:9:in `require'
zammad-railsserver_1    |       from bin/rails:9:in `<main>'
```
